replicaCount: 1

image:
  repository: nginx
  tag: "1.25.2"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: dev.my-demo-app.example.com
  path: /
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
